name: Deploy AMBA

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Login
        run: |
          az account show

      - name: Show Management Groups
        run: |
          az account management-group list -o table

      - name: Validate AMBA
        run: |
          az deployment mg validate \
            --management-group-id e81cb2c8-04d7-4cb1-84d3-f8ccf70961f6 \
            --location uksouth \
            --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json \
            --parameters @patterns/alz/alzArm.param.json
