name: Deploy AMBA

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate AMBA
        run: |
          az deployment mg validate \
            --management-group-id 557036d3-e691-43dc-822d-270ab850a823 \
            --name amba-id-amba-prod-001 \
            --location uksouth \
            --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json \
            --parameters @patterns/alz/alzArm.param.json
